### ISSUE TITLE
CI `test_all`:  docker-compose: command not found

### ISSUE THREAD

**Issue by DDvO** [siemens/gencmpclient#57]
Currently our CI fails, apparently due to missing docker-compose command.

**Comment by DDvO** [comment]
Thanks for that fix.

Yet what is the problem with the CloudCA test cases? How to fix those?

**Comment by rajeev-0** [comment]
I have created a issue (https://github.com/siemens/gencmpclient/issues/59) to follow it.

**Comment by DDvO** [comment]
Closing as completed
