### ISSUE TITLE
Handle NESTED messages more nicely

### ISSUE THREAD

**Issue by RufusJWB** [siemens/gencmpclient#65]
## Issue Report

When receiving a NESTED message from an upstream CA/RA the genCMPclient fails with a rather blunt error message.
![image](https://github.com/user-attachments/assets/62bfe375-af34-40cf-a600-900d22a565be)

## Expected Behavior

Unwrap the nested message and display the inner message

## Actual Behavior

Blunt error message

## Steps to Reproduce the Issue

n/a

### Proposed Resolution

n/a

**Comment by DDvO** [comment]
Isn't the error message very much to the point?
A productive CMP client does not need to be able to deal with nested messages.
Yet I agree that for testing purposes this can be nice to have.

Implementing such a testing/debugging support feature can easily take several work days,
taking into account code hygiene, adding tests and documentation, aligning this with OpenSSL, etc.
Moreover, at least one conceptual question would need to be clarified first, namely for which of 
the (possibly multiple) levels of nesting the client should demand/check message protection.

**Comment by RufusJWB** [comment]
Probably the message is okay. First I had some trouble understanding it, but I think it's fine. I'll close this ticket.
